### ISSUE TITLE
Gem issues / always "Setting up bundler"

### ISSUE THREAD

**Issue by maxlinc** [kitchenplan/kitchenplan#115]
I tried installing chef-dk via kitchen-plan using the [chef-dk cookbook](https://github.com/RoboticCheese/chef-dk-chef). That cookbook uses the omnijack gem and I ran into issues where it appeared to install omnijack but than couldn't find it. This may be related to https://github.com/kitchenplan/kitchenplan/issues/84 - I suspect it was installing to one ruby and then running chef with another.

I solved the issue by adding omnijack to my Gemfile but that has an annoying side-effect. kitchenplan tries to generate a new Gemfile every time I run `provision` and I need to tell it to keep my Gemfile rather than the re-generated version. Is it really necessary to generate a new Gemfile during `provision`? Wouldn't it make more sense to only do that as part of `setup`?

Here's what happens if I accept the overwrite, which undoes my omnijack workaround:

```
$ kitchenplan provision
  _  ___ _       _                      _             
 | |/ (_) |     | |                    | |            
 | ' / _| |_ ___| |__   ___ _ __  _ __ | | __ _ _ __  
 |  < | | __/ __| '_ \ / _ \ '_ \| '_ \| |/ _` | '_ \ 
 | . \| | || (__| | | |  __/ | | | |_) | | (_| | | | |
 |_|\_\_|\__\___|_| |_|\___|_| |_| .__/|_|\__,_|_| |_|
                                 | |                  
                                 |_|                  
                                                      
-> Making sure /opt exists and I can write to it
         run  sudo mkdir -p /opt from "."
         run  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null from "."
         run  sudo chown -R maxlincoln /opt from "."
-> Setting up bundler
    conflict  Gemfile
Overwrite /opt/kitchenplan/Gemfile? (enter "h" for help) [Ynaqdh] y
       force  Gemfile
         run  mkdir -p vendor/cache from "."
         run  rm -rf vendor/bundle/config from "."
         run  ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future bundle install --quiet --binstubs vendor/bin --path vendor/bundle from "."
-> Compiling configurations
         run  mkdir -p tmp from "."
-> Fetch the chef cookbooks
         run  vendor/bin/librarian-chef update 2>&1 > /dev/null from "."
         run  sudo vendor/bin/chef-solo   -c tmp/solo.rb -j tmp/kitchenplan-attributes.json -o applications::create_var_chef_cache,chef-dk::default,homebrewalt::default,nodejs::default,osxdefaults::set_terminal_profile,applications::sublime_text_3,osxdefaults::set_computer_name from "."
Starting Chef Client, version 11.18.6
[2015-02-23T14:14:14-05:00] WARN: Run List override has been provided.
[2015-02-23T14:14:14-05:00] WARN: Original Run List: []
[2015-02-23T14:14:14-05:00] WARN: Overridden Run List: [recipe[applications::create_var_chef_cache], recipe[chef-dk::default], recipe[homebrewalt::default], recipe[nodejs::default], recipe[osxdefaults::set_terminal_profile], recipe[applications::sublime_text_3], recipe[osxdefaults::set_computer_name]]
Compiling Cookbooks...
[2015-02-23T14:14:14-05:00] WARN: Cloning resource attributes for package[git] from prior resource (CHEF-3694)
[2015-02-23T14:14:14-05:00] WARN: Previous package[git]: /opt/kitchenplan/vendor/cookbooks/homebrewalt/recipes/default.rb:41:in `from_file'
[2015-02-23T14:14:14-05:00] WARN: Current  package[git]: /opt/kitchenplan/vendor/cookbooks/homebrewalt/recipes/default.rb:73:in `block in from_file'
Converging 54 resources
Recipe: applications::create_var_chef_cache
  * directory[/var/chef/cache] action create (up to date)
Recipe: chef-dk::default
  * chef_dk[chef_dk] action install
  Recipe: <Dynamically Defined Resource>
    * chef_gem[omnijack] action install
      - install version ~> 1.0 of package omnijack
    
    ================================================================================
    Error executing action `install` on resource 'chef_dk[chef_dk]'
    ================================================================================
    
    LoadError
    ---------
    cannot load such file -- omnijack
    
    Cookbook Trace:
    ---------------
    /opt/kitchenplan/vendor/cookbooks/chef-dk/libraries/provider_chef_dk.rb:181:in `require'
    /opt/kitchenplan/vendor/cookbooks/chef-dk/libraries/provider_chef_dk.rb:181:in `metadata'
    /opt/kitchenplan/vendor/cookbooks/chef-dk/libraries/provider_chef_dk.rb:61:in `action_install'
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchenplan/vendor/cookbooks/chef-dk/recipes/default.rb
    
     21: chef_dk 'chef_dk' do
     22:   version node['chef_dk']['version']
     23:   package_url node['chef_dk']['package_url']
     24:   global_shell_init node['chef_dk']['global_shell_init']
     25: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchenplan/vendor/cookbooks/chef-dk/recipes/default.rb:21:in `from_file'
    
    chef_dk("chef_dk") do
      provider Chef::Provider::ChefDk::MacOsX
      action :install
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name :"chef-dk"
      recipe_name "default"
      version "latest"
    end
    

Running handlers:
[2015-02-23T14:14:21-05:00] ERROR: Running exception handlers
Running handlers complete
[2015-02-23T14:14:21-05:00] ERROR: Exception handlers complete
[2015-02-23T14:14:21-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 1 resources updated in 9.315966 seconds
[2015-02-23T14:14:21-05:00] ERROR: chef_dk[chef_dk] (chef-dk::default line 21) had an error: LoadError: cannot load such file -- omnijack
[2015-02-23T14:14:21-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by roderik** [comment]
The thing is, the moment you install the kitchenplan gem and run setup (and probably the first provision), I know everything works. Let's say 2 months down the line I add something to kitchenplan that needs a new gem for provisioning, you then have config repo's that stop working.

I do find the whole ruby installing issues troubling, I hope https://github.com/kitchenplan/chef-applications/pull/115 will help

**Comment by maxlinc** [comment]
My description blur the lines between two issues. There are definitely some other issues with rubygems, and I admit that adding something to the Gemfile was more of a workaround than a solution, but I think the issues are already known and covered by issues like #84 or kitchenplan/chef-applications#115.

However, even if I never touch my Gemfile I feel that running "Setting up bundler" as part of provision seems is a waste of time. I think there is at least an argument to be made that it should be skipped if the `--no-fetch` option is used. If you don't want to grab new chef cookbooks then you probably don't want to grab a new version of chef (or any other gem), right?

Even if you do want new gems it looks like the only time that would happen is the first time you run after upgrading kitchenplan itself. It uses `bundle install` instead of `bundle update`, so you'll never get new gems unless the Gemfile changes. And the Gemfile comes from Gemfile.erb in the kitchenplan gem, which is currently just a static file (no actual ERB) so it will only change if the kitchenplan gem is upgraded.

So I agree with you with one minor addition (in bold). You said:
> 2 months down the line I add something to kitchenplan that needs a new gem for provisioning, you **upgrade kitchenplan** and then have config repo's that stop working

So, if you upgrade kitchenplan you need to ensure `/opt/kitchenplan/Gemfile` is updated and `bundle install` is run. I think it might make sense to document the upgrade process in the README.

It could be something like: `gem update kitchenplan; kitchenplan setup --upgrade`
Or perhaps a single command if it's possible: `kitchenplan upgrade`
