### ISSUE TITLE
Problems with brew-cask

### ISSUE THREAD

**Issue by spyro1st** [kitchenplan/kitchenplan#126]
Hi,

i use kitchenplan for quite a time now and provisioned some computers with it. Today i wanted to run on a new system but got stuck at:
- package[brew-cask] action install[2016-02-01T16:55:08+01:00] INFO: Processing package[brew-cask] action install (homebrewalt::default line 59)
  /usr/local
  Error: HOMEBREW_BREW_FILE was not exported! Please call bin/brew directly!
  # 
  # Error executing action `install` on resource 'package[brew-cask]'
  ## SystemExit
  
  exit
  ## Cookbook Trace:
  
  /opt/kitchenplan/vendor/cookbooks/homebrewalt/libraries/homebrew_package.rb:88:in `require'
  /opt/kitchenplan/vendor/cookbooks/homebrewalt/libraries/homebrew_package.rb:88:in`get_version_from_formula'
  /opt/kitchenplan/vendor/cookbooks/homebrewalt/libraries/homebrew_package.rb:68:in `current_installed_version'
  /opt/kitchenplan/vendor/cookbooks/homebrewalt/libraries/homebrew_package.rb:37:in`load_current_resource'
  ## Resource Declaration:
  # In /opt/kitchenplan/vendor/cookbooks/homebrewalt/recipes/default.rb
  
   59: package "brew-cask" do
   60:   options "--HEAD"
   61: end
   62: 
  ## Compiled Resource:
  # Declared in /opt/kitchenplan/vendor/cookbooks/homebrewalt/recipes/default.rb:59:in `from_file'
  
  package("brew-cask") do
    action :install
    retries 0
    retry_delay 2
    guard_interpreter :default
    options "--HEAD"
    package_name "brew-cask"
    timeout 900
    cookbook_name :homebrewalt
    recipe_name "default"
  end

[2016-02-01T16:55:08+01:00] INFO: Running queued delayed notifications before re-raising exception
[2016-02-01T16:55:08+01:00] DEBUG: Re-raising exception: SystemExit - package[brew-cask](homebrewalt::default line 59) had an error: SystemExit: exit
/usr/local/Library/Homebrew/utils.rb:117:in `exit'
  /usr/local/Library/Homebrew/utils.rb:117:in`odie'
  /usr/local/Library/Homebrew/config.rb:31:in `<top (required)>'
  /usr/local/Library/Homebrew/global.rb:18:in`require'
  /usr/local/Library/Homebrew/global.rb:18:in `<top (required)>'
  /opt/kitchenplan/vendor/cookbooks/homebrewalt/libraries/homebrew_package.rb:88:in`require'
  /opt/kitchenplan/vendor/cookbooks/homebrewalt/libraries/homebrew_package.rb:88:in `get_version_from_formula'
  /opt/kitchenplan/vendor/cookbooks/homebrewalt/libraries/homebrew_package.rb:68:in`current_installed_version'
  /opt/kitchenplan/vendor/cookbooks/homebrewalt/libraries/homebrew_package.rb:37:in `load_current_resource'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/provider.rb:104:in`run_action'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/resource.rb:648:in `run_action'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/runner.rb:49:in`run_action'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/runner.rb:81:in`each'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/runner.rb:81:in `block in converge'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/resource_collection.rb:98:in`block in execute_each_resource'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/resource_collection/stepable_iterator.rb:116:in`call_iterator_block'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/resource_collection/stepable_iterator.rb:104:in`iterate'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/resource_collection.rb:96:in`execute_each_resource'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/runner.rb:80:in `converge'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/client.rb:345:in`converge'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/client.rb:431:in `do_run'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/client.rb:213:in`block in run'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/client.rb:207:in `fork'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/client.rb:207:in`run'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/application.rb:236:in `run_chef_client'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/application/solo.rb:226:in`block in run_application'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/application/solo.rb:218:in `loop'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/application/solo.rb:218:in`run_application'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/lib/chef/application.rb:55:in `run'
  /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/chef-11.18.12/bin/chef-solo:25:in`<top (required)>'
  vendor/bin/chef-solo:16:in `load'
  vendor/bin/chef-solo:16:in`<main>'

I can't figure out whats the problem. Installing casks by hand works without any problems. I guess it's a problem with homebrew-alt but i'm not sure.

I saw superlumic but i don't have the time now to migrate all my configuration.

**Comment by spyro1st** [comment]
Here the output on pastern without markdown formatting problems:
http://pastebin.com/aN1JXKQF

**Comment by mangan77** [comment]
+1
