### ISSUE TITLE
kitchenplan provision No such file or directory - /opt/kitchenplan/Cheffile (Errno::ENOENT)

### ISSUE THREAD

**Issue by agenteo** [kitchenplan/kitchenplan#73]
osx 10.9.2

When I run:

```
$ ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future kitchenplan provision
```

I get:

```
-> Fetch the chef cookbooks
         run  vendor/bin/librarian-chef install --clean --quiet --path=vendor/cookbooks from "/opt/kitchenplan"
/opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl/receiver.rb:30:in `read': No such file or directory - /opt/kitchenplan/Cheffile (Errno::ENOENT)
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl/receiver.rb:30:in `run'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl.rb:79:in `block in run'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl.rb:73:in `tap'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl.rb:73:in `run'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl.rb:17:in `run'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/environment.rb:148:in `dsl'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/specfile.rb:15:in `read'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:13:in `run'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/cli.rb:41:in `install'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /opt/kitchenplan/vendor/bundle/ruby/2.0.0/gems/librarian-chef-0.0.2/bin/librarian-chef:7:in `<top (required)>'
    from vendor/bin/librarian-chef:16:in `load'
    from vendor/bin/librarian-chef:16:in `<main>'
```

**Comment by pal** [comment]
What was the problem @agenteo? I get the same on a new machine.

**Comment by mehrenreich** [comment]
I just removed the `:ref` from the `homebrewalt` line in /opt/kitchenplan/Cheffile. It worked then:

`cookbook "homebrewalt",           :github => "kitchenplan/chef-homebrewalt"`
